// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZvwR4a6qHZI6DzhFdM1SiiRviRkQQAO4',
    appId: '1:282828731461:web:71b644f728236a21bf1f2c',
    messagingSenderId: '282828731461',
    projectId: 'security-system-fe80a',
    authDomain: 'security-system-fe80a.firebaseapp.com',
    storageBucket: 'security-system-fe80a.appspot.com',
    measurementId: 'G-77SV834TT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptz1_ETRD_GruTHUai6TuQuEsWBnCCzI',
    appId: '1:282828731461:android:2b62060ef832cfc9bf1f2c',
    messagingSenderId: '282828731461',
    projectId: 'security-system-fe80a',
    storageBucket: 'security-system-fe80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTOV2oIM7QL21f6kGpAvrNdMFU4pwGac',
    appId: '1:282828731461:ios:ee12c0bd69c739f0bf1f2c',
    messagingSenderId: '282828731461',
    projectId: 'security-system-fe80a',
    storageBucket: 'security-system-fe80a.appspot.com',
    androidClientId: '282828731461-7nem4io6d5fbrrrk4l678iqsr5ckg990.apps.googleusercontent.com',
    iosClientId: '282828731461-8sp37ujpvifq64omlgr86p8e5m2p6v7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.securitySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfTOV2oIM7QL21f6kGpAvrNdMFU4pwGac',
    appId: '1:282828731461:ios:7c2fb36e11909be1bf1f2c',
    messagingSenderId: '282828731461',
    projectId: 'security-system-fe80a',
    storageBucket: 'security-system-fe80a.appspot.com',
    androidClientId: '282828731461-7nem4io6d5fbrrrk4l678iqsr5ckg990.apps.googleusercontent.com',
    iosClientId: '282828731461-ptab4u2camm6upgdh6ccth75tdjfg1jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.securitySystem.RunnerTests',
  );
}
